### ISSUE TITLE
 input fields  problem

### ISSUE THREAD

**Issue by GhostRock37** [pia-lab/pialab-docker#3] opened 2018-06-06 09:17 UTC
Hello,

I have a problem when I try to enter text in the input fields of the PIA : 
the entry is blocked just after the first character entered.
the problem occurs on all input fields!

thank you !

**Comment by PapsOu** [comment] 2018-06-06 09:28
Hello.

I cannot going further after login. I think there is a problem with your user permissions.

The app cannot fetch the profile's information or any pias.

Please check your utilisateur1@test.fr roles.

**Comment by GhostRock37** [comment] 2018-06-06 09:31
yes sorry, it's ok now !

**Comment by PapsOu** [comment] 2018-06-06 09:33
OK Cool. I'm closing the issue.

You should edit your first message and remove URLs and user's login informations to avoid anybody attacking your instance.

**Comment by GhostRock37** [comment] 2018-06-06 09:34
Now, i still have the problem ! When i say it's ok now, it's for the account => you can log into the app 
Can you re-open the issue ?

**Comment by PapsOu** [comment] 2018-06-06 09:42
It's strange because I have changed your `test` PIA name by `test123`.

**Comment by GhostRock37** [comment] 2018-06-06 09:46
yes but if you open the pia (edit the pia) and you add some text in the field , you will have a problem !

**Comment by PapsOu** [comment] 2018-06-06 09:49
OK I can reproduce your bug.

We will check that as soon as possible.

Thanks for reporting.

**Comment by GhostRock37** [comment] 2018-06-06 09:57
Thanks for your help :+1: 
Do you still need the account on my instance?

**Comment by PapsOu** [comment] 2018-06-06 10:35
@GhostRock37 : No thank you, we don't need your account because we have reproduced the bug.

We'll keep you in touch.

**Comment by PapsOu** [comment] 2018-06-06 10:43
Please tell me if your edited PIA has a progress of 100% (the green bar visible on the pia card) ?

Because I can edit elements on PIA that are in a progress of 0% , but for those with progress of 100%, I can edit an element till it is not fully fetched.

So, I think the case you describe (typing one letter and blocking) correspond to that case.

Please confirm me that you don't have this problem with a PIA lesser than 100% progress.

**Comment by GhostRock37** [comment] 2018-06-06 12:14
I have the problem with 2 PIA that are in a progress 0%  ( you can always login to my instance if you want !)

**Comment by PapsOu** [comment] 2018-06-06 13:09
OK Well, I've checked something about user's permissions.

Please tell me exactly witch permissions are assigned to user `utilisateur1@test.fr`.

I can reproduce the problem when having role DPO.

When switching to role `Data controller`, I can now edit these fields.

![20180606-150558](https://user-images.githubusercontent.com/5792207/41039990-6dba59bc-699b-11e8-8621-33984521d60e.png)

Please note that a user must have only one role (the form is allowing multiple roles but it is something that will be corrected soon). The role `ROLE_USER` will be removed from this form.

**Comment by GhostRock37** [comment] 2018-06-06 13:22
yes, utilisateur1@test.fr was DPO 
![utilisateur1](https://user-images.githubusercontent.com/25516319/41040539-fe271228-699c-11e8-9f70-78d005550aca.JPG)

Now, i affect the role Data controler, and its OK !!!!! Yes !!! Bravo !!  (you can test):
![data controler](https://user-images.githubusercontent.com/25516319/41040733-870803fe-699d-11e8-948f-b5471f4c0316.JPG)

**Comment by PapsOu** [comment] 2018-06-06 13:27
Great.

If the issue is « solved », feel free to close it.

Thank you again for reporting this issue.

**Comment by GhostRock37** [comment] 2018-06-06 13:33
ok, but i have one question : should the DPO role be able to complete the fields of the PIA no? The role controller is only to comment on the PIA no?

what is the purpose of the DPO role?

**Comment by PapsOu** [comment] 2018-06-06 13:34
@RomainSanchez : Could you answer this question ? I cannot :sweat_drops:

**Comment by RomainSanchez** [comment] 2018-06-06 13:47
@GhostRock37 The basic process is as follows:
- DPO creates pia
- Data controller fills the pia
- DPO evaluates

**Closed as completed by RomainSanchez** 2018-06-06 13:47 UTC
Labels: bug

**Comment by GhostRock37** [comment] 2018-06-07 06:01
@RomainSanchez ok thank for your help !

You leave this running for the DPO role? Do not you think that the seizure fields should be grayed out for the DPO if it does not have to fill them? The fact that the filling is possible but that it hangs just after the first character is a bit special?

thanks again
